---
# Change pip's cache directory to be inside the project directory
# since gitlab ci can only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - unit_test
  - integration_test

test:py27:
  stage: unit_test
  image: python:2.7.11-slim
  before_script:
    # pip 21.0 does not support py2 but the default pip in this container
    # is too old and fails. Hence the pip version must be 20.3.4.
    - pip install --trusted-host pypi.python.org --upgrade pip==20.3.4
    - python --version ; pip --version
    - pip install virtualenv
    - virtualenv venv27
    - source venv27/bin/activate
  script:
    - pip install -r tests/requirements-py27.txt
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  cache:
    key:
      files:
        - tests/requirements-py27.txt
    paths:
      - venv27/
      - .cache/pip


test:py38:
  stage: unit_test
  image: python:3.8.10-slim
  before_script:
    - pip install --upgrade pip
    - python --version ; pip --version
    - pip install virtualenv
    - virtualenv venv38
    - source venv38/bin/activate
  script:
    - pip install -r tests/requirements-py38.txt
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  cache:
    key:
      files:
        - tests/requirements-py38.txt
    paths:
      - venv38/
      - .cache/pip


# =============================================================================
# Integration Test Template
# =============================================================================
.integration_template: &integration_template
  stage: integration_test
  image: python:3.8.10-slim
  resource_group: aci_fabric_tests
  before_script:
    - echo 'ACQUIRE {http::proxy "$apt_proxy"}' >> /etc/apt/apt.conf
    - echo -e "$apt_source" > /etc/apt/sources.list
    - apt update
    - apt install -y curl
    - pip install --upgrade pip
    - python --version ; pip --version
    - pip install virtualenv
    - virtualenv venv38-integration
    - source venv38-integration/bin/activate
    - cd tests
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/requirements.txt/raw?ref=main" -o requirements.txt'
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/runner.py/raw?ref=main" -o runner.py'
    - pip install -r requirements.txt
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - $CI_PROJECT_DIR/tests/*.log
      - $CI_PROJECT_DIR/tests/*.tgz
  cache:
    key:
      files:
        - tests/requirements.txt
    paths:
      - venv38-integration/
      - .cache/pip
  timeout: 45m
  retry:
    max: 1
    when: runner_system_failure

# =============================================================================
# Integration Tests - 5.x Internal Upgrades
# =============================================================================
test:integration:5.2.4d-to-5.2.8f:
  <<: *integration_template
  variables:
    FABRIC_CVERSION: "5.2(4d)"
    FABRIC_TVERSION: "5.2(8f)"
  script:
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/test_fabrics.yaml/raw?ref=main" -o test_fabrics.yaml'
    - python3 runner.py -f ../aci-preupgrade-validation-script.py -i test_fabrics.yaml -k $decode_key --cversion "$FABRIC_CVERSION" --tversion "$FABRIC_TVERSION"

# =============================================================================
# Integration Tests - 5.x to 6.0.x Upgrades
# =============================================================================
test:integration:5.2.4d-to-6.0.2h:
  <<: *integration_template
  variables:
    FABRIC_CVERSION: "5.2(4d)"
    FABRIC_TVERSION: "6.0(2h)"
  script:
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/test_fabrics.yaml/raw?ref=main" -o test_fabrics.yaml'
    - python3 runner.py -f ../aci-preupgrade-validation-script.py -i test_fabrics.yaml -k $decode_key --cversion "$FABRIC_CVERSION" --tversion "$FABRIC_TVERSION"

test:integration:5.2.6e-to-6.0.5a:
  <<: *integration_template
  variables:
    FABRIC_CVERSION: "5.2(6e)"
    FABRIC_TVERSION: "6.0(5a)"
  script:
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/test_fabrics.yaml/raw?ref=main" -o test_fabrics.yaml'
    - python3 runner.py -f ../aci-preupgrade-validation-script.py -i test_fabrics.yaml -k $decode_key --cversion "$FABRIC_CVERSION" --tversion "$FABRIC_TVERSION"

# =============================================================================
# Integration Tests - 5.x to 6.1.x Upgrades
# =============================================================================
test:integration:5.2.8d-to-6.1.1f:
  <<: *integration_template
  variables:
    FABRIC_CVERSION: "5.2(8d)"
    FABRIC_TVERSION: "6.1(1f)"
  script:
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/test_fabrics.yaml/raw?ref=main" -o test_fabrics.yaml'
    - python3 runner.py -f ../aci-preupgrade-validation-script.py -i test_fabrics.yaml -k $decode_key --cversion "$FABRIC_CVERSION" --tversion "$FABRIC_TVERSION"

test:integration:5.3.2d-to-6.1.4h:
  <<: *integration_template
  variables:
    FABRIC_CVERSION: "5.3(2d)"
    FABRIC_TVERSION: "6.1(4h)"
  script:
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/test_fabrics.yaml/raw?ref=main" -o test_fabrics.yaml'
    - python3 runner.py -f ../aci-preupgrade-validation-script.py -i test_fabrics.yaml -k $decode_key --cversion "$FABRIC_CVERSION" --tversion "$FABRIC_TVERSION"

# =============================================================================
# Integration Tests - 6.x Internal Upgrades
# =============================================================================
test:integration:6.0.2a-to-6.1.4h:
  <<: *integration_template
  variables:
    FABRIC_CVERSION: "6.0(2a)"
    FABRIC_TVERSION: "6.1(4h)"
  script:
    - 'curl --header "PRIVATE-TOKEN: $integration_repo_token" "$repo_url/test_fabrics.yaml/raw?ref=main" -o test_fabrics.yaml'
    - python3 runner.py -f ../aci-preupgrade-validation-script.py -i test_fabrics.yaml -k $decode_key --cversion "$FABRIC_CVERSION" --tversion "$FABRIC_TVERSION"
